import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { parseStartToken } from '@/lib/telegramNotify'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

async function reply(chatId: number, text: string) {
  const token = process.env.CUSTOMER_TELEGRAM_BOT_TOKEN
  await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ chat_id: chatId, text }),
  })
}

// Telegram calls this for every update to @invoices_notify_bot. This bot is
// send-and-confirm only (see design doc's "Explicitly out of scope") -- the
// only inbound interaction handled is "/start <token>" from the deep-link
// generated by /api/telegram-connect/init. Anything else gets a short
// explanatory reply, not silence -- a curious user who messages the bot
// directly (no deep-link) deserves to know what it's for.
export async function POST(req: NextRequest) {
  const secret = req.headers.get('x-telegram-bot-api-secret-token')
  if (!secret || secret !== process.env.TELEGRAM_NOTIFY_WEBHOOK_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const update = await req.json()
  const msg = update.message
  const text = msg?.text
  const chatId = msg?.chat?.id
  if (typeof text !== 'string' || typeof chatId !== 'number') {
    return NextResponse.json({ ok: true })
  }

  const token = parseStartToken(text)
  if (!token) {
    await reply(chatId, 'Этот бот используется только для уведомлений invoices.kz. Чтобы подключить его к своему аккаунту, перейдите в Профиль → Уведомления и нажмите «Подключить».')
    return NextResponse.json({ ok: true })
  }

  const { data: owner, error } = await supabase
    .from('profiles')
    .update({ telegram_chat_id: String(chatId), telegram_connect_token: null })
    .eq('telegram_connect_token', token)
    .select('id')
    .maybeSingle()

  if (error) {
    console.error('telegram-notify-webhook: link update failed:', error.message)
    await reply(chatId, 'Не удалось подключить — попробуйте ещё раз из приложения.')
    return NextResponse.json({ ok: true })
  }

  if (!owner) {
    await reply(chatId, 'Ссылка недействительна, вернитесь в приложение и нажмите «Подключить» ещё раз.')
    return NextResponse.json({ ok: true })
  }

  await reply(chatId, '✅ Telegram подключён к вашему аккаунту invoices.kz.')
  return NextResponse.json({ ok: true })
}
