import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { parseStartToken } from '@/lib/telegramNotify'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

async function reply(chatId: number, text: string) {
  const token = process.env.CUSTOMER_TELEGRAM_BOT_TOKEN
  await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ chat_id: chatId, text }),
  })
}

// Telegram calls this for every update to @invoices_notify_bot. This bot is
// send-and-confirm only (see design doc's "Explicitly out of scope") -- the
// only inbound interaction handled is "/start <token>" from the deep-link
// generated by /api/telegram-connect/init. Anything else gets a short
// explanatory reply, not silence -- a curious user who messages the bot
// directly (no deep-link) deserves to know what it's for.
export async function POST(req: NextRequest) {
  const secret = req.headers.get('x-telegram-bot-api-secret-token')
  if (!secret || secret !== process.env.TELEGRAM_NOTIFY_WEBHOOK_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const update = await req.json()
  const msg = update.message
  const text = msg?.text
  const chatId = msg?.chat?.id
  if (typeof text !== 'string' || typeof chatId !== 'number') {
    return NextResponse.json({ ok: true })
  }

  const token = parseStartToken(text)

  // Отдельная ветка для входа в планировщик салона (planner_<code>) -- это
  // НЕ обычная привязка аккаунта (та ветка ниже), а проверка "совпадает ли
  // сканирующий Telegram-аккаунт с уже привязанным владельцем салона". При
  // несовпадении строку planner_sessions не трогаем -- настоящий владелец
  // должен суметь отсканировать через мгновение и получить доступ, ошибка
  // чужого скана не должна портить код.
  if (token?.startsWith('planner_')) {
    const code = token.slice('planner_'.length)

    const { data: session } = await supabase
      .from('planner_sessions')
      .select('site_id, status, expires_at')
      .eq('code', code)
      .maybeSingle()

    const stillValid = session?.status === 'pending' && new Date(session.expires_at).getTime() > Date.now()
    const site = stillValid
      ? (await supabase.from('salon_sites').select('slug, owner_profile_id').eq('id', session.site_id).maybeSingle()).data
      : null
    const owner = site?.owner_profile_id
      ? (await supabase.from('profiles').select('telegram_chat_id').eq('id', site.owner_profile_id).maybeSingle()).data
      : null

    if (site && owner?.telegram_chat_id === String(chatId)) {
      const { data: claimed } = await supabase
        .from('planner_sessions')
        .update({ status: 'confirmed', owner_profile_id: site.owner_profile_id })
        .eq('code', code)
        .eq('status', 'pending')
        .gt('expires_at', new Date().toISOString())
        .select('id')
        .maybeSingle()

      if (claimed) {
        await reply(chatId, '✅ Вход в планировщик подтверждён — вернитесь к экрану, он откроется сам.')
      } else {
        await reply(chatId, 'Код уже использован или истёк — обновите QR на экране планировщика и отсканируйте заново.')
      }
    } else if (site) {
      await reply(chatId, `Этот QR предназначен для владельца салона. Страница салона: https://${site.slug}.invoices.kz`)
    } else {
      await reply(chatId, 'Код недействителен или истёк — обновите QR на экране планировщика.')
    }

    return NextResponse.json({ ok: true })
  }

  if (!token) {
    await reply(chatId, 'Этот бот используется только для уведомлений invoices.kz. Чтобы подключить его к своему аккаунту, перейдите в Профиль → Уведомления и нажмите «Подключить».')
    return NextResponse.json({ ok: true })
  }

  const { data: owner, error } = await supabase
    .from('profiles')
    .update({ telegram_chat_id: String(chatId), telegram_connect_token: null })
    .eq('telegram_connect_token', token)
    .select('id')
    .maybeSingle()

  if (error) {
    console.error('telegram-notify-webhook: link update failed:', error.message)
    await reply(chatId, 'Не удалось подключить — попробуйте ещё раз из приложения.')
    return NextResponse.json({ ok: true })
  }

  if (!owner) {
    await reply(chatId, 'Ссылка недействительна, вернитесь в приложение и нажмите «Подключить» ещё раз.')
    return NextResponse.json({ ok: true })
  }

  await reply(chatId, '✅ Telegram подключён к вашему аккаунту invoices.kz.')
  return NextResponse.json({ ok: true })
}
