import { describe, it, expect } from 'vitest'
import { X509Certificate } from 'crypto'
import { extractSignatureAndCertificate } from './extractSignatureAndCertificate'

// The founder's actual signature (a real CMS SignedData) from Task 1's live
// spike: signing a real government sample ЭСФ XML with his real GOST
// certificate via SIGEX QR/eGov mobile on 2026-09-12. Independently verified
// with `openssl cms -cmsout -print -inform DER` before writing this test --
// see this task's report for the full openssl output. Using the real
// artifact rather than a hand-built fake CMS blob, since a synthetic one
// risks not matching real-world structural quirks (this exact signature
// carries an embedded RFC3161 timestamp token in its unsignedAttrs, which a
// naive fixture would likely omit).
const REAL_CMS_SIGNATURE_BASE64 =
  'MIIPYgYJKoZIhvcNAQcCoIIPUzCCD08CAQExDjAMBggqgw4DCgEDAwUAMAsGCSqGSIb3DQEHAaCCBFQwggRQMIIDuKADAgECAhQZ8DVF95e0I+gAa9nN4E04a4YVkDAOBgoqgw4DCgEBAgMCBQAwWDFJMEcGA1UEAwxA0rDQm9Ci0KLQq9KaINCa0KPTmNCb0JDQndCU0KvQoNCj0KjQqyDQntCg0KLQkNCb0KvSmiAoR09TVCkgMjAyMjELMAkGA1UEBhMCS1owHhcNMjUxMDI4MDkwNDQzWhcNMjYxMDI4MDkwNDQzWjCBljEoMCYGA1UEAwwf0JDQkdCY0JvQrNCR0JDQldCSINCQ0JvQmNCl0JDQnTEbMBkGA1UEBAwS0JDQkdCY0JvQrNCR0JDQldCSMRgwFgYDVQQFEw9JSU44OTA1MjUzNTAxNDMxCzAJBgNVBAYTAktaMSYwJAYDVQQqDB3QnNCj0KXQkNCc0JXQlC3QkNCb0JjQldCS0JjQpzCBrDAjBgkqgw4DCgEBAgIwFgYKKoMOAwoBAQICAQYIKoMOAwoBAwMDgYQABIGA3UAfiwe1fHnDF3OjTOHbxMsjZpy0fhrO6C2qVjHkd+TLZhITFqcOu30/smU7NpNuEdeUQZGBeJSGc9JnZg04Sf+EKqB6KGJ9SFa1hhxO7qX1ob+XKtpOxN2x83ubUHczwXs8nUJelOfmkomBZ2M6DOa+RbeK8FAaLfkCokClDs2jggHHMIIBwzAOBgNVHQ8BAf8EBAMCA8gwJwYDVR0lBCAwHgYIKoMOAwMEAwIGCCsGAQUFBwMEBggqgw4DAwQBATA4BgNVHSAEMTAvMC0GBiqDDgMDAjAjMCEGCCsGAQUFBwIBFhVodHRwOi8vcGtpLmdvdi5rei9jcHMwOAYDVR0fBDEwLzAtoCugKYYnaHR0cDovL2NybC5wa2kuZ292Lmt6L25jYV9nb3N0XzIwMjIuY3JsMDoGA1UdLgQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwucGtpLmdvdi5rei9uY2FfZF9nb3N0XzIwMjIuY3JsMGgGCCsGAQUFBwEBBFwwWjAiBggrBgEFBQcwAYYWaHR0cDovL29jc3AucGtpLmdvdi5rejA0BggrBgEFBQcwAoYoaHR0cDovL3BraS5nb3Yua3ovY2VydC9uY2FfZ29zdF8yMDIyLmNlcjAWBgNVHREEDzANgQthbGlfOUBiay5ydTAdBgNVHQ4EFgQUifA1RfeXtCPoAGvZzeBNOGuGFZAwHwYDVR0jBBgwFoAU/jC+n8iQYz8f/1o8DLDIX0xtFwgwFgYGKoMOAwMFBAwwCgYIKoMOAwMFAQEwDgYKKoMOAwoBAQIDAgUAA4GBABPJVhyXVIIRQ/yHwRSJ9I4uay1M7Z858dbyaiMzyz7/uZFjjCurXY0R9/EXNQH3p93NCRVz8PSxSeCSyLCJ+/vi9j8EvdpIQZn1S3N98qxE1XZ3V/Lt3KnLmpmzPqjKoYYUAyYYneREl6ZwAxtt+5OnqR/ifiIPJQF+h3a8je30MYIK0zCCCs8CAQEwcDBYMUkwRwYDVQQDDEDSsNCb0KLQotCr0pog0JrQo9OY0JvQkNCd0JTQq9Cg0KPQqNCrINCe0KDQotCQ0JvQq9KaIChHT1NUKSAyMDIyMQswCQYDVQQGEwJLWgIUGfA1RfeXtCPoAGvZzeBNOGuGFZAwDAYIKoMOAwoBAwMFAKCBwjAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yNjA5MTIwODQzMjZaMDcGCyqGSIb3DQEJEAIvMSgwJjAkMCIEICfniqipQqFhU9GPjsh9lYUtknvV+n825SI5jEY/FCdnME8GCSqGSIb3DQEJBDFCBEBavggqOjZ4QD7uq1mKTbzEqincu/dxofbOM2LO+OyjV8h9mSTtb5T/SRx0sHhwPAdNR7Xjt9z/Ffyk1kcvByLXMA4GCiqDDgMKAQECAwIFAASBgLdzPPV9otS99x60BYecB8S2FJbntbH4iEcio8IPpJ0RsIDbJMTuNvJrB1oc+gkwlV0ALnNZxyBQ8xjIOeYVkj4ok+QWB+hOnI/wjpIq+sloNZrSb+GPfIDxTyv+BX6I1nF56w91YJL/K0DH19CkiwSErmdqyiBk2BNfhpIPhZdjoYII8DCCCOwGCyqGSIb3DQEJEAIOMYII2zCCCNcGCSqGSIb3DQEHAqCCCMgwggjEAgEDMQ8wDQYJYIZIAWUDBAIBBQAwfQYLKoZIhvcNAQkQAQSgbgRsMGoCAQEGCCqDDgMDAgYCMDEwDQYJYIZIAWUDBAIBBQAEIGisfvkaNKDjVLki0/LZ7V6qt5egRAzfZYzWFCvG/HwdAhST1Uw+5X5a/EHtNk9Ad0fULj7rZRgPMjAyNjA5MTIwODQzMjZaAgFAoIIF9DCCBfAwggPYoAMCAQICFC2MhVNesix8zVjMlN+SGgmTiSj3MA0GCSqGSIb3DQEBCwUAMFcxSDBGBgNVBAMMP9Kw0JvQotCi0KvSmiDQmtCj05jQm9CQ0J3QlNCr0KDQo9Co0Ksg0J7QoNCi0JDQm9Cr0pogKFJTQSkgMjAyMjELMAkGA1UEBhMCS1owHhcNMjUxMDI4MDYyNjA0WhcNMjgxMDI3MDYyNjA0WjBuMSAwHgYDVQQDDBdUSU1FLVNUQU1QSU5HIEFVVEhPUklUWTELMAkGA1UEBhMCS1oxPTA7BgNVBAoMNNKw0JvQotCi0KvSmiDQmtCj05jQm9CQ0J3QlNCr0KDQo9Co0Ksg0J7QoNCi0JDQm9Cr0powggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCGfhueEectrd9QYASVhtYaZ3r66JQuf6YYXbb+UUQBjuv8PHtVNBcfAa0gdw72GQsEgI9ta7dWITLs/tKWXQVf53Y0ky97THPyqg2Z7GW7O82eKIbLurTEfia4+YVAlWTZdoyXR9aikQUBPptk22+g3vqJqcrNXU9FwOfeIwdBvr0NmchJ4o/JJbmISVozzmJ+8brNMVuTXKoT14din4PXr7vSgVMUYUcUpGvJHDA4wnzstjn1RZ84AQqndG8hv4bTM90ak7FhT0s18E/vBoAjG9Vh73WhgjFJOeln/gx1XOgWEqvqjutKIPu2X5s3msv+afY5akG5fjDng9o1EbcDAgMBAAGjggGbMIIBlzAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwNwYDVR0fBDAwLjAsoCqgKIYmaHR0cDovL2NybC5wa2kuZ292Lmt6L25jYV9yc2FfMjAyMi5jcmwwOQYDVR0uBDIwMDAuoCygKoYoaHR0cDovL2NybC5wa2kuZ292Lmt6L25jYV9kX3JzYV8yMDIyLmNybDBnBggrBgEFBQcBAQRbMFkwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLnBraS5nb3Yua3owMwYIKwYBBQUHMAKGJ2h0dHA6Ly9wa2kuZ292Lmt6L2NlcnQvbmNhX3JzYV8yMDIyLmNlcjA4BgNVHSAEMTAvMC0GBiqDDgMDAjAjMCEGCCsGAQUFBwIBFhVodHRwOi8vcGtpLmdvdi5rei9jcHMwHQYDVR0OBBYEFC2MhVNesix8zVjMlN+SGgmTiSj3MB8GA1UdIwQYMBaAFNyuJNdJsmSA0t43Izw+pFFdtVrHMBYGBiqDDgMDBQQMMAoGCCqDDgMDBQEBMA0GCSqGSIb3DQEBCwUAA4ICAQA8irnIkbYIV4MEyERjH0dfu0wuSVK+zPrf48REOlMoIhsRxVlmHGuvBNInLSu0VQbJON/kCQ4v8XRu8sVr4Ob0AMeU1/+0SEwQDCncGpBSR0FwvorA2ntvcGSgwqiTYtLAv+BzQgDZS7bEdwyKKUYqBsq2z3rSQSQQhobD2NMbi4/9l74qqFUmg8bxo+wUS3OGa1DN0fRonuONFJQ//diuHRBSr2NDNcRnn8UozT0ExPxTPlTtohmr0fq6cMMR3saru/dRMBH/1FU9bc159y28Ede7dufI+eY0t/7cGVYYFPjLA7xC2eFfkHesbDyK1nN6/Mh6DhuPg9w4qkESoRLEVYCHXZyMDWMcAAUGo9pDzHzkpQuemBgY+JWUfbNLqwlSqWDFN3D7YRoqx+4TYCAqwP2bv8I/sQp1DqzQd8aOoz1xlUqd+qaLg5CHrzzfrVPJ60duC9blXjeuEPqWgVrERZW7air1IMPJYj5ewZ8Bn1feVzXuijVyVipyytW7PzuWPiKlrD5ikendw2Zt2wlR6+aXTAszxPZR/7qIO2Nrowc6AjmpT0c+5htiNUZ1HvdmWWNnkpvmQ7OWqCndUfDyP4VIKVyb+uRmG5T58EEE+nD8jkFZFnb9iB67Npnaiuc3SZLlDxxCsksI0aSKL8YRWxk+dZH93162tCxGleRB7TGCAjUwggIxAgEBMG8wVzFIMEYGA1UEAww/0rDQm9Ci0KLQq9KaINCa0KPTmNCb0JDQndCU0KvQoNCj0KjQqyDQntCg0KLQkNCb0KvSmiAoUlNBKSAyMDIyMQswCQYDVQQGEwJLWgIULYyFU16yLHzNWMyU35IaCZOJKPcwDQYJYIZIAWUDBAIBBQCggZgwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0yNjA5MTIwODQzMjZaMCsGCyqGSIb3DQEJEAIMMRwwGjAYMBYEFAW0nVP2BmJvmMmOLwmU7YXj2f1ZMC8GCSqGSIb3DQEJBDEiBCDrSSo9fUAs/c5HjW6r1k04xrHvhwtMqqQl0ANDfyvBXjANBgkqhkiG9w0BAQsFAASCAQB80HSbdXog893SM2mOnIL7ouHTvkXPGwz9Xec6hbt2f/VTk1dHxiOOuTv3bSlfVRDGkBIlsRNYY8kLp2+xti6+6O2pUbudqq+3xH06N6AgpfT5sw1W43bcHIw+KOzCk2Wr4jfapnRseWpa1YloxgEaxPWhTG0t5unh4Pwa0RYqHBgc1SK4eFzKKn0PbOIcm77/A47LHY3C/ekLKDN16nk/D/iH7IwdhzMlmQtjNDNABtbDra5vX1QEF+tPwXbvsRFTnBJssFdIAoDG0b3V3iqpTXBqxnT4HtKXDq6yq65tXkBFYmQNocivtEWFiw0lonDNbE7MWKLEcXf4+JkBrtRR'

describe('extractSignatureAndCertificate', () => {
  it('pulls a plausible raw signature (NOT a whole CMS envelope) out of the real signature', () => {
    const { signatureBase64 } = extractSignatureAndCertificate(REAL_CMS_SIGNATURE_BASE64)
    const sigBytes = Buffer.from(signatureBase64, 'base64')
    // Confirmed independently with `openssl cms -cmsout -print -inform DER`
    // on this exact fixture: signerInfos[0].signature is a 128-byte OCTET
    // STRING (GOST algorithm) -- nowhere near the ~3.9KB whole CMS blob.
    expect(sigBytes.byteLength).toBeGreaterThanOrEqual(32)
    expect(sigBytes.byteLength).toBeLessThanOrEqual(256)
    expect(sigBytes.byteLength).toBe(128)
  })

  it("extracts the signer's own embedded certificate, matching the known signer", () => {
    const { certificateBase64 } = extractSignatureAndCertificate(REAL_CMS_SIGNATURE_BASE64)
    const certDer = Buffer.from(certificateBase64, 'base64')
    // Parsed with Node's built-in X509Certificate rather than adding a
    // second certificate-parsing dependency alongside pkijs/asn1js.
    const cert = new X509Certificate(certDer)
    expect(cert.subject).toContain('CN=АБИЛЬБАЕВ АЛИХАН')
    expect(cert.subject).toContain('serialNumber=IIN890525350143')
  })

  it('throws on garbage input instead of silently returning nonsense', () => {
    expect(() => extractSignatureAndCertificate(Buffer.from('not a cms blob').toString('base64'))).toThrow()
  })
})
