import { NextResponse } from 'next/server'
import { rotatePublishToken } from '@/lib/instagramPublishToken'
import { rotateConnectionTokens } from '@/lib/aiAgent/connectionTokens'
import { sendTelegramNotification } from '@/lib/telegramNotify'

// Keeps the Instagram publishing token alive.
//
// Daily, because the window that matters is measured in days and the work is a
// single HTTP call. rotatePublishToken decides whether anything is actually
// due, so most runs do nothing.
//
// The founder is told only when a rotation FAILS. A token that stops rotating
// is invisible until it hits Meta's 60-day cliff, past which no code can
// recover it — a new marker has to be generated by hand in the App Dashboard.
// A quiet daily success needs no notification; a failure needs one while there
// are still weeks of runway left.
export async function GET(request: Request) {
  const authHeader = request.headers.get('authorization')
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const result = await rotatePublishToken()

  // Customers' Instagram connections expire the same way and were never
  // renewed either — an agent would just fall silent 60 days after it was
  // connected. Run after the publishing token and independently of it: one
  // failing must not skip the other.
  const connections = await rotateConnectionTokens()
  if (connections.failed.length > 0) {
    console.error('cron instagram-token: connection refresh failures:', JSON.stringify(connections.failed))
    await sendTelegramNotification(
      process.env.TELEGRAM_CHAT_ID!,
      `⚠️ Не удалось продлить токен Instagram у ${connections.failed.length} подключений: ` +
      connections.failed.map(f => f.account || f.id).join(', ') +
      '\n\nЭти агенты перестанут отвечать клиентам, когда токен истечёт. ' +
      'Владельцу нужно переподключить Instagram в настройках агента.'
    ).catch((e: any) => console.error('cron instagram-token: telegram notice failed:', e?.message || e))
  } else if (connections.refreshed > 0) {
    console.log('cron instagram-token: refreshed', connections.refreshed, 'connection token(s)')
  }

  if (result.status === 'failed' || result.status === 'no_token') {
    const detail = result.status === 'failed'
      ? result.error
      : 'INSTAGRAM_ACCESS_TOKEN не задан и в базе токена нет'
    console.error('cron instagram-token:', detail)
    await sendTelegramNotification(
      process.env.TELEGRAM_CHAT_ID!,
      `⚠️ Не удалось продлить маркер Instagram: ${detail}\n\n` +
      'Публикация постов перестанет работать, когда маркер истечёт. ' +
      'Если продление не восстановится, выпустите новый маркер в кабинете Meta ' +
      '(Instagram → API setup → Сгенерируйте маркеры доступа) и обновите INSTAGRAM_ACCESS_TOKEN.'
    ).catch((e: any) => console.error('cron instagram-token: telegram notice failed:', e?.message || e))
  } else {
    console.log('cron instagram-token:', JSON.stringify(result))
  }

  return NextResponse.json({ publishToken: result, connections })
}
